### ISSUE TITLE
Resolving Test Failure in Travis

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Sql#9]
Hi @pmjones , 

In the https://github.com/auraphp/Aura.Sql/blob/master/tests/bootstrap.php , we have currently the username and password for mysql , postgres, but for travis-ci the username and passwords are different .

Can you make the necessary changes on your database system or add the tests/bootstrap.php to .gitignore files , so we don't get any issues ?

You can check the correct values in 

https://github.com/harikt/Aura.Sql/blob/travis/.travis.yml

or for your convenience  

```
- DB=mysql:
  adapter: mysql2
  database: test
  username: 
  encoding: utf8
- DB=postgres:
  adapter: postgresql
  database: test
  username: postgres
```

The https://github.com/harikt/Aura.Sql/blob/travis/tests/bootstrap.php I was using has a username `root` for mysql , but when I checked recently the root from travis-ci seems missing in their documentation. But still this works .

See http://travis-ci.org/#!/harikt/Aura.Sql

Thank you
